name: Build Surge_pxx

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Clone Theos and set up environment
        run: |
          # Clone Theos into the home directory
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          # Set THEOS environment variable and update PATH
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "PATH=$HOME/theos/bin:$PATH" >> $GITHUB_ENV

      - name: Build OpenSSL for iOS
        run: |
          # Clone and build OpenSSL to $HOME/openssl-ios
          git clone https://github.com/openssl/openssl.git $HOME/openssl
          cd $HOME/openssl
          export PLATFORM="iPhoneOS"
          export SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          export CC="$(xcrun --sdk iphoneos -f clang)"
          export ARCHS="arm64 arm64e"
          export CFLAGS="-arch arm64 -arch arm64e -isysroot $SDK -miphoneos-version-min=14.0"
          export LDFLAGS="-arch arm64 -arch arm64e -isysroot $SDK"
          ./Configure ios64-cross no-shared no-dso no-hw no-engine --prefix=$HOME/openssl-ios
          make clean
          make -j$(sysctl -n hw.ncpu)
          make install

      - name: Patch Makefile for OpenSSL path (rootless)
        run: |
          # Replace the hard-coded OpenSSL path with the runner’s home directory path
          sed -i '' "s#/Users/pxx917144686/openssl-ios#$HOME/openssl-ios#g" rootless/Makefile

      - name: Install ldid
        run: brew install ldid

      - name: Build Surge_pxx (rootless)
        working-directory: rootless
        run: |
          # Build using THEOS_OPENSSL_DIR variable if needed
          make THEOS_OPENSSL_DIR=$HOME/openssl-ios

      - name: Create builds directory and copy built file
        run: |
          mkdir -p builds
          cp rootless/.theos/obj/debug/Surge.dylib builds/

      - name: Commit build artifact
        uses: EndBug/add-and-commit@v9
        with:
          message: "Add Surge build artifact from GitHub Actions build"
          add: "builds/Surge.dylib"
